.travis.yml, Makefile, clients/idler_test.go, clients/tenant_test.go, proxy/proxy_test.go
=> Issue #104 Removing wrong dependency of vendor target

README.md
=> Issue #76 Updating README

cico_build_deploy.sh, cmd/osio/cmd/jwt.go, cmd/osio/cmd/root.go, cmd/osio/cmd/token.go, internal/proxy/proxy.go, internal/util/common.go, internal/util/jwt.go, internal/util/osio_token.go, scripts/siegeJenkins.sh, scripts/webhook-migration/Dockerfile, scripts/webhook-migration/README.md, scripts/webhook-migration/updateWebhooks.sh, scripts/webhook-migration/webhook-migration.job.yaml
@vpavlin - Still work in progress, but have a look and let me know whether I am on the right track. As discussed I am now building a container, so that we can run the migration inside the cluster. 
Works nicely so far from my machine as well. 
Addresses issue #94
=> Issue #94 Dockerfile and scripts for web hook migration

internal/clients/idler.go, internal/proxy/proxy.go
=> Issue #161 Calling explicitly unidle when Jenkins in idle state

cmd/osio/cmd/token.go, internal/util/common.go, internal/util/osio_token.go, scripts/webhook-migration/README.md, scripts/webhook-migration/updateWebhooks.sh, scripts/webhook-migration/webhook-migration.job.yaml
Based on pull request #173. Addresses issue #172
=> Issue #172 Making sure that private key id can be provided as well

.gitignore, cmd/fabric8-jenkins-proxy/main.go, cmd/fabric8-jenkins-proxy/main_test.go, internal/configuration/configuration.go, internal/configuration/env_config.go, internal/configuration/env_config_test.go, internal/proxy/proxy.go, internal/storage/db_store_test.go, internal/storage/store.go, internal/testutils/common.go, internal/testutils/mock/mock_config.go, internal/util/multi_error.go, internal/util/reflect.go, internal/util/reflect_test.go, internal/util/validations.go, internal/util/validations_test.go, scripts/setupLocalProxy.sh, scripts/stopLocalProxy.sh
- Aligning with Idler implementation
- Updating tests
- Adding some helper functions
- Making some improvements to setupLocalProxy.sh
- Deleting obsolete stopLocalProxy.sh
=> Issue #152 Making Configuration an interface

internal/configuration/env_config.go, internal/configuration/env_config_test.go
=> Issue #180 Making sure OSO cluster inormation is properly loaded

README.md, scripts/setupLocalProxy.sh
- Modified local proxy script to install jq
- Modified documentation regarding running proxy locally
Fixes #210
=> Issue #210 Added docs regarding running proxy locally

Dockerfile.deploy, Gopkg.lock, internal/router/router.go, internal/router/router_test.go, scripts/pcp/jenkins-proxy+pmcd.sh, scripts/pcp/pcp.repo
Importing what I have been doing on idler side,
Fixes #200
=> Issue #200 Integrate with PCP

Makefile
- Remove golint dependency temporarily
=> Issue #237 Remove golint dependency

internal/clients/idler.go, internal/proxy/proxy.go, static/html/index.html
Idler would be giving 503 if Cluster Tenant Resource Capacity is
Reached. Modified Unidle function to handle that
Now waiting template will show the message "Cluster Tenant resource
capacity for current cluster is full, please wait...", if
Cluster Capacity is reached
#243
=> Issue #243 Show if Cluster Capacity is Reached

internal/proxy/proxy.go
=> Issue #257 Avoid CORS

Gopkg.lock, Gopkg.toml, cmd/fabric8-jenkins-proxy/main.go, cmd/fabric8-jenkins-proxy/main_cors_test.go, internal/proxy/proxy.go, internal/router/router.go
This fixes #257 by reusing a CORS library
=> Issue #257: Using Go CORS Handler

internal/clients/idler.go, internal/proxy/proxy.go
Proxy uses `!idler.IsIdle()` to check if pods are running but that is
wrong as IsIdle can return `false` if pods are just `starting` or
`terminating`. Hence lets use the new api in idler status to check if the
Pods are actually running.
=> Fix #270 Use new idler status api to check pod state

openshift/jenkins-proxy-api.route.yaml, openshift/jenkins-proxy.app.yaml
This commit edits openshift config to add Jenkins API on port :9092
For #281
=> Issue #281 Edit openshift config to add Jenkins API

README.md, internal/jenkinsapi/jenkinsapi.go, internal/router/router_test.go, internal/util/logging/request.go, scripts/setupLocalProxy.sh
Correct misspells error reported by https://pypi.org/project/misspellings/.
=> Fix #293 Misspellings in the comment and doc

README.md
=> Issue #291 Document Jenkins start API

cmd/fabric8-jenkins-proxy/main_cors_test.go
- if the test fails its easy to identify which case is failing
- avoids DRY(dont repeat yourself) and makes it more readable
Fixes #309
=> Fix #309 Refactored the cors test

Makefile
This closes openshiftio/openshift.io#4466 and closes #326
=> Remove validate_commits

Makefile, internal/proxy/ui_requests.go
This closes #324 and closes openshiftio/openshift.io#4465
=> Use golang.org/x/lint/golint to install golint

.ike-prow/test-keeper.yaml
Don't validate docs static script and Makefile
This closes openshiftio/openshift.io#4467 and closes #328
=> Add ike test-keeper.yaml

Gopkg.lock, internal/auth/auth.go
This closes openshiftio/openshift.io#4477 and closes #331
=> Fix formatting of Log.info to use Log.infof

internal/proxy/github.go, internal/proxy/github_test.go, internal/proxy/jenkins.go, internal/proxy/mock_proxy.go, internal/proxy/ui_requests_test.go, internal/wit/mock_wit.go
The code was using an empty namespace, fixed that
Fixes https://github.com/openshiftio/openshift.io/issues/4600
=> Webhook from github to jenkins fails with 500 Status
